name: Build and deploy Laravel to Azure Web App - InventarioCIC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql, zip, intl, gd

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # NODE + VITE
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies and build
        run: |
          npm install
          npm run build

      # Laravel cache optimizations
      - name: Optimize Laravel
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan config:cache
          php artisan route:cache

      # Prepare artifact
      - name: Create deployment zip
        run: zip -r deploy.zip . -x "node_modules/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-artifact
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_37F829BDDF1A4D16BEC720A00356F2F7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CB6320BB29184F02BF5F6DA99FE8DD92 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FBAF385B98AE4C8097A4B0E77C846A15 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'InventarioCIC'
          slot-name: 'Production'
          package: deploy.zip
